version: '3'

services:

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql 
      - ./init-scripts:/docker-entrypoint-initdb.d 
    environment:
      - MYSQL_DATABASE=nodedb 
      - MYSQL_ROOT_PASSWORD=root                 
    networks:
      - node-network-work2    

  nodeapp:
    build:
      context: node
    container_name: nodeapp
    networks:
      - node-network-work2
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    volumes:  
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    expose:
      - 3000
    depends_on:
       - db

  nginx:
    #image: nginx:latest
    build:
      context: nginx
    container_name: nginx-proxy
    networks:
      - node-network-work2    
    ports:
      - "8080:80"    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: ["wait-for", "nodeapp:3000", "-t", "40", "--", "nginx", "-g", "daemon off;"]    
    depends_on:
      - nodeapp

networks:
  node-network-work2: 
    driver: bridge
